### ISSUE TITLE
Error on preview

### ISSUE THREAD

**Issue by tcardel** [grafikr/shopify-actions#171]
While deploy action works fine by itself with no errors, an error occurs on preview, with the same repo.

Logs with error:

```
Run grafikr/shopify-actions@v1
  with:
    ACTION: PREVIEW
    GITHUB_TOKEN: ***
Copying directory "undefined" to "***"
Error: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
```

The directory I used for the theme is on "build", as used in the examples, mostly because I think that #170 could some have relation to this.

**Comment by andershagbard** [comment]
Thanks for raising the issue. Will resolve asap

**Comment by andershagbard** [comment]
I don't think has to do with the `BUILD_DIR` variable. This variable is only used to store the temporary theme files.

This issue comes if you don't have a `directory` in your environment from the `config.yml`. I'll come up with a fix for this.
