### ISSUE TITLE
Create Preview - Deploy theme error

### ISSUE THREAD

**Issue by tmmgrafikr** [grafikr/shopify-actions#96]
Fails with a **429** code, which translates to, **_too many requests, above the API Rate limit_**
https://github.com/grafikr/butlerstudios/actions/runs/3334949012/jobs/5518419208#step:5:7

**Comment by andershagbard** [comment]
This may be because that we exhaust api limit on `theme deploy`, but Shopify doesn't enforce their rate limit on this api endpoint.

Then when we try to do a request to create a theme, it enforces their rate limiting.

Should be easy enough to fix.
